 <!DOCTYPE html>                                                                                                                                                                                                                                                                                                                                                                             
 <%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>                                                                                                                                                                                                                                                                                                                  
 <%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>                                                                                                                                                                                                                                                                                                                          
 <%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>                                                                                                                                                                                                                                                                                                                        
 <%                                                                                                                                                                                                                                                                                                                                                                                          
 	String path = request.getContextPath();                                                                                                                                                                                                                                                                                                                                                 
 %>                                                                                                                                                                                                                                                                                                                                                                                          
 <!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                             
 <!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                             
 <!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                             
 <!-- BEGIN HEAD -->                                                                                                                                                                                                                                                                                                                                                                         
 <head>                                                                                                                                                                                                                                                                                                                                                                                      
 	<meta charset="utf-8" />                                                                                                                                                                                                                                                                                                                                                              
 	<title>后台管理系统</title>                                                                                                                                                                                                                                                                                                                                                             
 	<meta content="width=device-width, initial-scale=1.0" name="viewport" />                                                                                                                                                                                                                                                                                                            
 	<meta content="" name="description" />                                                                                                                                                                                                                                                                                                                                              
 	<meta content="" name="author" />                                                                                                                                                                                                                                                                                                                                                   
 	<!-- BEGIN GLOBAL MANDATORY STYLES -->                                                                                                                                                                                                                                                                                                                                                  
 	<link href="<%=path%>/resources/admin/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>                                                                                                                                                                                                                                                                                   
 	<link href="<%=path%>/resources/admin/css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css"/>                                                                                                                                                                                                                                                                        
 	<link href="<%=path%>/resources/admin/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>                                                                                                                                                                                                                                                                                
 	<link href="<%=path%>/resources/admin/css/style-metro.css" rel="stylesheet" type="text/css"/>                                                                                                                                                                                                                                                                                     
 	<link href="<%=path%>/resources/admin/css/style.css" rel="stylesheet" type="text/css"/>                                                                                                                                                                                                                                                                                           
 	<link href="<%=path%>/resources/admin/css/style-responsive.css" rel="stylesheet" type="text/css"/>                                                                                                                                                                                                                                                                                
 	<link href="<%=path%>/resources/admin/css/default-main.css" rel="stylesheet" type="text/css" id="style_color"/>                                                                                                                                                                                                                                                                 
 	<link href="<%=path%>/resources/admin/css/uniform.default.css" rel="stylesheet" type="text/css"/>                                                                                                                                                                                                                                                                                 
 	<link href="<%=path%>/resources/admin/css/tip.css" rel="stylesheet">                                                                                                                                                                                                                                                                                                                
 	<!-- END GLOBAL MANDATORY STYLES -->                                                                                                                                                                                                                                                                                                                                                    
 	<!-- BEGIN PAGE LEVEL STYLES -->                                                                                                                                                                                                                                                                                                                                                        
 	<link rel="stylesheet" type="text/css" href="<%=path%>/resources/admin/css/select2_metro.css" />                                                                                                                                                                                                                                                                                  
 	<link rel="stylesheet" href="<%=path%>/resources/admin/css/DT_bootstrap.css" />                                                                                                                                                                                                                                                                                                     
 	<!-- END PAGE LEVEL STYLES -->                                                                                                                                                                                                                                                                                                                                                          
 	<link rel="shortcut icon" href="resources/image/favicon.ico" />                                                                                                                                                                                                                                                                                                                     
 	</head>                                                                                                                                                                                                                                                                                                                                                                                 
 	<body class="page-header-fixed">                                                                                                                                                                                                                                                                                                                                                      
 	<!-- BEGIN PAGE TITLE & BREADCRUMB-->                                                                                                                                                                                                                                                                                                                                                   
 						<h3 class="page-title">                                                                                                                                                                                                                                                                                                                                           
 						</h3>                                                                                                                                                                                                                                                                                                                                                               
 						<ul class="breadcrumb">                                                                                                                                                                                                                                                                                                                                           
 							<li>                                                                                                                                                                                                                                                                                                                                                            
 								<i class="icon-home"></i>                                                                                                                                                                                                                                                                                                                                 
 								<a href="<%=path%>/admin/articleCategory/articleCategoryList">课件基本信息管理</a>                                                                                                                                                                                                                                                                            
 								<i class="icon-angle-right"></i>                                                                                                                                                                                                                                                                                                                          
 							</li>                                                                                                                                                                                                                                                                                                                                                           
 							<li><a href="#">课件基本信息添加</a></li>                                                                                                                                                                                                                                                                                                                         
 						</ul>                                                                                                                                                                                                                                                                                                                                                               
 						<!-- END PAGE TITLE & BREADCRUMB-->                                                                                                                                                                                                                                                                                                                                 
 	 					<div class="row-fluid">                                                                                                                                                                                                                                                                                                                                           
 		<!-- BEGIN EXAMPLE TABLE PORTLET-->                                                                                                                                                                                                                                                                                                                                                 
 						<div class="portlet box blue">                                                                                                                                                                                                                                                                                                                                    
 							<div class="portlet-title">                                                                                                                                                                                                                                                                                                                                   
 								<div class="caption">                                                                                                                                                                                                                                                                                                                                     
 								<!--<i class="icon-globe"></i>-->                                                                                                                                                                                                                                                                                                                         
 								课件基本信息添加                                                                                                                                                                                                                                                                                                                                                
 								</div>                                                                                                                                                                                                                                                                                                                                                      
 								<div class="actions">                                                                                                                                                                                                                                                                                                                                     
 								 <div class="input-prepend">                                                                                                                                                                                                                                                                                                                              
 										</div>			                                                                                                                                                                                                                                                                                                                                    
 								</div>                                                                                                                                                                                                                                                                                                                                                      
 							</div>                                                                                                                                                                                                                                                                                                                                                          
 							<div class="portlet-body">                                                                                                                                                                                                                                                                                                                                    
 							<form action="<%=path%>/admin/articleCategory/save" method="post" id="acForm">                                                                                                                                                                                                                                                                            
 							<input type="hidden" id="grade" name="grade" value="0">                                                                                                                                                                                                                                                                                                 
 							<input type="hidden" id="parent" name="parent" value="">                                                                                                                                                                                                                                                                                                
 									 	<table class="table table-bordered " id="sample_2">                                                                                                                                                                                                                                                                                             
 								     <tbody>                                                                                                                                                                                                                                                                                                                                                
 										<tr>                                                                                                                                                                                                                                                                                                                                                
 											<th>名称</th>                                                                                                                                                                                                                                                                                                                                   
 											<td>                                                                                                                                                                                                                                                                                                                                            
 												<input class="m-wrap medium" size="10"  name="name" type="text" placeholder="课件基本信息名称" />                                                                                                                                                                                                                                     
 											</td>                                                                                                                                                                                                                                                                                                                                           
 											<th class="hidden-480">课件基本信息</th>                                                                                                                                                                                                                                                                                                          
 											<td class="hidden-480">                                                                                                                                                                                                                                                                                                                       
 													<div class="btn-group">                                                                                                                                                                                                                                                                                                               
 													<span style = "border:1px solid #000000;overflow:hidden;width:198px">                                                                                                                                                                                                                                                                 
 													  <select  name="id"   style="scrollbar{overflow:auto;SCROLLBAR-FACE-COLOR: #e8e8e8;SCROLLBAR-HIGHLIGHT-COLOR: #dddddd;SCROLLBAR-SHADOW-COLOR: #CCC;SCROLLBAR-3DLIGHT-COLOR: #FFFFFF;SCROLLBAR-ARROW-COLOR: #AAA;SCROLLBAR-TRACK-COLOR: #FFFFFF;SCROLLBAR-DARKSHADOW-COLOR: #FFF;SCROLLBAR-BASE-COLOR: #FFF;}">                     
 										  				<option value="0" selected>顶级分类</option>                                                                                                                                                                                                                                                                                      
 										  				  <c:forEach var="ac" items="${aclist}">                                                                                                                                                                                                                                                                                        
 															 <option value="${ac.id}">                                                                                                                                                                                                                                                                                                    
 															  <c:choose>                                                                                                                                                                                                                                                                                                                    
 														       <c:when test="${ac.grade==0}">                                                                                                                                                                                                                                                                                             
 														       </c:when>                                                                                                                                                                                                                                                                                                                    
 														       <c:when test="${ac.grade==1}">                                                                                                                                                                                                                                                                                             
 														              &nbsp;&nbsp;&nbsp;&nbsp;                                                                                                                                                                                                                                                                                              
 														       </c:when>                                                                                                                                                                                                                                                                                                                    
 														        <c:when test="${ac.grade==2}">                                                                                                                                                                                                                                                                                            
 														              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                                                                                                                                                                                                                                                                      
 														       </c:when>                                                                                                                                                                                                                                                                                                                    
 														       <c:otherwise>                                                                                                                                                                                                                                                                                                                
 														              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                                                                                                                                                                                                                                                          
 														       </c:otherwise>                                                                                                                                                                                                                                                                                                               
 																 </c:choose>${ac.name}&nbsp;&nbsp;|&nbsp;&nbsp;${ac.orders}                                                                                                                                                                                                                                                                 
 															 </option>                                                                                                                                                                                                                                                                                                                      
 														  </c:forEach>                                                                                                                                                                                                                                                                                                                      
 										  		 	  </select>                                                                                                                                                                                                                                                                                                                             
 										  		 	</span>                                                                                                                                                                                                                                                                                                                                 
 											  </div>                                                                                                                                                                                                                                                                                                                                        
 											</td>                                                                                                                                                                                                                                                                                                                                           
 										</tr>                                                                                                                                                                                                                                                                                                                                               
 										<tr>                                                                                                                                                                                                                                                                                                                                                
 											<th>排序</th>                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                             
 											<td colspan="3">                                                                                                                                                                                                                                                                                                                              
 												<input class="m-wrap medium" size="10" type="text"  name="orders" placeholder="排序" />                                                                                                                                                                                                                                           
 											</td>                                                                                                                                                                                                                                                                                                                                           
 										</tr>                                                                                                                                                                                                                                                                                                                                               
 										<tr>                                                                                                                                                                                                                                                                                                                                                
 											<th>页面标题</th>                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                             
 											<td  colspan="3" class="hidden-480">                                                                                                                                                                                                                                                                                                        
 												<input type="text" class="m-wrap span12" size="16"  name="seoTitle" type="text" placeholder="页面标题" >                                                                                                                                                                                                                        
 											</td>                                                                                                                                                                                                                                                                                                                                           
 										</tr>                                                                                                                                                                                                                                                                                                                                               
 										<tr>                                                                                                                                                                                                                                                                                                                                                
 											<th>页面关键词</th>                                                                                                                                                                                                                                                                                                                             
 											<td  colspan="3" class="hidden-480">                                                                                                                                                                                                                                                                                                        
 												<input type="text" class="m-wrap span12" size="16"  name="seoKeywords" type="text" placeholder="页面关键词" >                                                                                                                                                                                                                   
 											</td>                                                                                                                                                                                                                                                                                                                                           
 										</tr>                                                                                                                                                                                                                                                                                                                                               
 										<tr>                                                                                                                                                                                                                                                                                                                                                
 											<th>页面描述</th>                                                                                                                                                                                                                                                                                                                               
 											<td  colspan="3" class="hidden-480">                                                                                                                                                                                                                                                                                                        
 												<input type="text" class="m-wrap span12" size="16"    name="seoDescription" type="text" placeholder="页面描述" >                                                                                                                                                                                                                
 											</td>                                                                                                                                                                                                                                                                                                                                           
 										</tr>		                                                                                                                                                                                                                                                                                                                                        
 									</tbody>                                                                                                                                                                                                                                                                                                                                                
 								</table>                                                                                                                                                                                                                                                                                                                                                    
 										<div class="form-actions">                                                                                                                                                                                                                                                                                                                        
 													&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                                                                                                                                                                                                                                                                                                    
 													<button class="btn blue" type="button" onclick="location.href='<%=path%>/admin/articleCategory/articleCategoryList'">返&nbsp;&nbsp;回</button>                                                                                                                                                                                    
 													&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                                                                                                                                                                                                                                                                                                    
 													<button class="btn blue" type="submit"><i class="icon-ok"></i> 确&nbsp;&nbsp;定</button>                                                                                                                                                                                                                                          
 													&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                                                                                                                                                                                                                                                                                                    
 										 </div>                                                                                                                                                                                                                                                                                                                                             
 							     </form>                                                                                                                                                                                                                                                                                                                                                    
 								                                                                                                                                                                                                                                                                                                                                                            
 							</div>                                                                                                                                                                                                                                                                                                                                                          
 						<!-- END EXAMPLE TABLE PORTLET-->                                                                                                                                                                                                                                                                                                                                   
 			</div>	                                                                                                                                                                                                                                                                                                                                                                        
 			</div>                                                                                                                                                                                                                                                                                                                                                                          
 	                                                                                                                                                                                                                                                                                                                                                                                        
 	<script src="<%=path%>/resources/admin/js/jquery-1.10.1.min.js" type="text/javascript"></script>                                                                                                                                                                                                                                                                                    
 	<script src="<%=path%>/resources/admin/js/jquery.validate.js" type="text/javascript"></script>                                                                                                                                                                                                                                                                                      
 	<script type='text/javascript' src='<%=path%>/resources/admin/js/messages_zh.js'></script>                                                                                                                                                                                                                                                                                              
     <!-- IMPORTANT! Load jquery-ui-1.10.1.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->                                                                                                                                                                                                                                                
     <script src="<%=path%>/resources/admin/js/bootstrap.min.js" type="text/javascript"></script>                                                                                                                                                                                                                                                                                        
 	<!--[if lt IE 9]>                                                                                                                                                                                                                                                                                                                                                                       
 	<script src="<%=path%>/resources/admin/js/excanvas.min.js"></script>                                                                                                                                                                                                                                                                                                                  
 	<script src="<%=path%>/resources/admin/js/respond.min.js"></script>                                                                                                                                                                                                                                                                                                                   
 	<![endif]-->                                                                                                                                                                                                                                                                                                                                                                            
 	<script src="<%=path%>/resources/admin/js/jquery.slimscroll.min.js" type="text/javascript"></script>                                                                                                                                                                                                                                                                                
     <!-- END CORE PLUGINS -->                                                                                                                                                                                                                                                                                                                                                               
 	<!-- BEGIN PAGE LEVEL PLUGINS -->                                                                                                                                                                                                                                                                                                                                                       
 	<script type="text/javascript" src="<%=path%>/resources/admin/js/select2.min.js"></script>                                                                                                                                                                                                                                                                                          
 	<script type="text/javascript" src="<%=path%>/resources/admin/js/jquery.dataTables.min.js"></script>                                                                                                                                                                                                                                                                                
 	<script type="text/javascript" src="<%=path%>/resources/admin/js/DT_bootstrap.js"></script>                                                                                                                                                                                                                                                                                         
 	<!-- END PAGE LEVEL PLUGINS -->                                                                                                                                                                                                                                                                                                                                                         
 	<!-- BEGIN PAGE LEVEL SCRIPTS -->                                                                                                                                                                                                                                                                                                                                                       
 	<script src="<%=path%>/resources/admin/js/app.js"></script>                                                                                                                                                                                                                                                                                                                           
 	<script src="<%=path%>/resources/admin/js/table-advanced.js"></script>                                                                                                                                                                                                                                                                                                                
  <script>                                                                                                                                                                                                                                                                                                                                                                                   
 		jQuery(document).ready(function() {                                                                                                                                                                                                                                                                                                                                                 
 		   App.init();                                                                                                                                                                                                                                                                                                                                                                      
 		   //TableAdvanced.init();                                                                                                                                                                                                                                                                                                                                                          
 		});                                                                                                                                                                                                                                                                                                                                                                                 
 		  $().ready(function() {                                                                                                                                                                                                                                                                                                                                                            
  		   $("#acForm").validate({                                                                                                                                                                                                                                                                                                                                                        
 				  // 定义验证规则                                                                                                                                                                                                                                                                                                                                                           
 			    rules: {                                                                                                                                                                                                                                                                                                                                                                    
 			         name:{ required:true,minlength:2,maxlength:80},                                                                                                                                                                                                                                                                                                                        
 			         orders: {  required: true, isDigits:true, minlength: 1,maxlength:50}                                                                                                                                                                                                                                                                                                   
 			    },                                                                                                                                                                                                                                                                                                                                                                          
 			     messages: {  //提示信息                                                                                                                                                                                                                                                                                                                                                    
 			         name:{required: "请输入文章分类名称",minlength: "文章分类名称至少需要2个字符",maxlength:"文章分类名称输入字符不能超过80个字符"},                                                                                                                                                                                                                                 
 			         orders: { required: "请输入排序",isDigits:"排序只能输入数字",minlength: "排序至少需要1个字符",maxlength:"排序输入字符不能超过80个字符"}                                                                                                                                                                                                                        
 			        }                                                                                                                                                                                                                                                                                                                                                                       
 		  });                                                                                                                                                                                                                                                                                                                                                                               
 	 });                                                                                                                                                                                                                                                                                                                                                                                    
 	</script>                                                                                                                                                                                                                                                                                                                                                                               
 <script type="text/javascript">  var _gaq = _gaq || [];  _gaq.push(['_setAccount', 'UA-37564768-1']);                                                                                                                                                                                                                                                                                     
 _gaq.push(['_setDomainName', 'keenthemes.com']);  _gaq.push(['_setAllowLinker', true]);  _gaq.push(['_trackPageview']);                                                                                                                                                                                                                                                                     
   (function() {    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;                                                                                                                                                                                                                                                                                 
   ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';                                                                                                                                                                                                                                                                             
   var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);  })();</script>                                                                                                                                                                                                                                                                                     
   </body>                                                                                                                                                                                                                                                                                                                                                                                   
 <!-- END BODY -->                                                                                                                                                                                                                                                                                                                                                                           
 </html>                                                                                                                                                                                                                                                                                                                                                                                     

